import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { createClient } from "@/utils/supabase/server";

// Context
import Shell from "@/components/store/shell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {data, error} = await supabase.auth.getUser(); // simple.

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* There are actually some values that we will need from the server in order to load the correct state. Nice and easy. */}
        <Shell supabase_user={data}>
          {children}
        </Shell>
      </body>
    </html>
  );
}

// enough of all the conventions. 
// I should name my app's files as I see fit.